export const SET_PARKING_METADATA = "SET_PARKING_METADATA";
export const CLICK_MARKER = "CLICK_MARKER";
export const CLICK_LIST = "CLICK_LIST";
export const SHOW_DETAIL = "SHOW_DETAIL";
export const SET_MARKER_DATA = "SET_MARKER_DATA";


