export const SET_AIR_METADATA = "SET_AIR_METADATA";
export const CLICK_MARKER = "CLICK_MARKER";
export const CLICK_LIST = "CLICK_LIST";
export const SHOW_DETAIL = "SHOW_DETAIL";
export const SET_MARKER_DATA = "SET_MARKER_DATA";
export const SET_FILTER_DATE = "SET_FILTER_DATE";
export const SET_SCREEN_SIZE = "SET_SCREEN_SIZE";
export const SET_MOLECULE_TYPE = "SET_MOLECULE_TYPE";
export const SET_PLOT_TYPE = "SET_PLOT_TYPE";

